### ISSUE TITLE
metrics.json

### ISSUE THREAD

**Issue by IbtihalFerwana** [malteos/aspect-document-similarity#2]
Hello, 

Is it possible I see how you are organizing your `metrics.json` file?

**Comment by IbtihalFerwana** [comment]
I have a question, 
what would determine a classification threshold? `classification_threshold`
you are using 0, did you experiment with other values?

**Comment by malteos** [comment]
The `metrics.json` is the output of `predictions.metrics` which is the flattened classification report (precision, recall etc. for each class):

```python
flatten(classification_report(
                y_true=p.label_ids,
                y_pred=predicted_labels,
                target_names=self.label_classes,
                zero_division=0,
                output_dict=True)
```

See https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
